name: Format

on:
  push:
    branches:
      - main

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Xcode Select
        run: sudo xcode-select -s /Applications/Xcode_16.0.app
      - name: Tap
        run: brew install swift-format
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
